version: '1'
services:
  backend:
    build:
      context: ./backend/webAPI/src
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    env_file:
      - ./backend/webAPI/src/.env
  redis:
    image: redis:7.0.15-alpine3.20
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication
    ports:
      - 5432:5432